= Cheatsheets

[[BotOptions]]
== BotOptions

++++
 @author <a href="mailto:julien@julienviet.com">Julien Viet</a>
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[httpServerOptions]]`httpServerOptions`|`link:dataobjects.html#HttpServerOptions[HttpServerOptions]`|-
|[[name]]`name`|`String`|-
|===

[[ReceiveOptions]]
== ReceiveOptions

++++
 @author <a href="mailto:julien@julienviet.com">Julien Viet</a>
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[chatId]]`chatId`|`String`|
+++
Set the id that uniquely identifies where the message is coming from. This id can be used for idenfying the source
 of this message or to post a message some time later to the chat.
+++
|[[timeout]]`timeout`|`Number (long)`|
+++
The timeout in millis to wait until a message is considered not processed by the bot.
+++
|===

[[ClientOptions]]
== ClientOptions

++++
 @author <a href="mailto:julien@julienviet.com">Julien Viet</a>
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[name]]`name`|`String`|-
|[[reconnectPeriod]]`reconnectPeriod`|`Number (long)`|-
|===

[[SendOptions]]
== SendOptions

++++
 @author <a href="mailto:julien@julienviet.com">Julien Viet</a>
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[chatId]]`chatId`|`String`|
+++
Set the id that identifies the chat where this message should be sent.
+++
|===

